spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 2e5f40b98dddd734c054ea8a9501e68f
            client-secret: qvW6dMOKJloIoS7Jl5iKBuTJLHNooziL
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope: profile_nickname
  mvc:
    view:
      prefix: /templates/
      suffix: .html